# Generated by Django 5.2 on 2025-05-12 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('total_points', models.IntegerField()),
                ('attempts_limit', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courses')),
            ],
            options={
                'db_table': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(max_length=50)),
                ('lab_number', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('step_file', models.BinaryField(blank=True, null=True)),
                ('module_id', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.DO_NOTHING, to='university.modules')),
            ],
            options={
                'db_table': 'Steps',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isu_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('solution_data', models.TextField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('attempts_left', models.IntegerField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.modules')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.studentprofile')),
            ],
            options={
                'db_table': 'Solutions',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed_labs', models.IntegerField(blank=True, null=True)),
                ('total_labs', models.IntegerField(blank=True, null=True)),
                ('average_grade', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.studentprofile')),
            ],
            options={
                'db_table': 'Progress',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='university.studentprofile', verbose_name='Студенты курса'),
        ),
        migrations.CreateModel(
            name='StudentStepAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.steps')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'step')},
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='attempts',
            field=models.ManyToManyField(related_name='student_attempts', through='university.StudentStepAttempt', to='university.steps'),
        ),
        migrations.AddField(
            model_name='steps',
            name='attemts',
            field=models.ManyToManyField(related_name='steps', through='university.StudentStepAttempt', to='university.studentprofile'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.teacherprofile'),
        ),
    ]
