# Generated by Django 5.2.1 on 2025-05-10 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('total_points', models.IntegerField()),
                ('attempts_limit', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courses')),
            ],
            options={
                'db_table': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(max_length=50)),
                ('lab_number', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('step_file', models.BinaryField(blank=True, null=True)),
                ('module_id', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.DO_NOTHING, to='university.modules')),
            ],
            options={
                'db_table': 'Steps',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('isu_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.groups')),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('solution_data', models.TextField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('attempts_left', models.IntegerField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.modules')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.students')),
            ],
            options={
                'db_table': 'Solutions',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed_labs', models.IntegerField(blank=True, null=True)),
                ('total_labs', models.IntegerField(blank=True, null=True)),
                ('average_grade', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.students')),
            ],
            options={
                'db_table': 'Progress',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='university.students', verbose_name='Студенты курса'),
        ),
        migrations.CreateModel(
            name='StudentStepAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.steps')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.students')),
            ],
            options={
                'unique_together': {('student', 'step')},
            },
        ),
        migrations.AddField(
            model_name='students',
            name='attempts',
            field=models.ManyToManyField(related_name='student_attempts', through='university.StudentStepAttempt', to='university.steps'),
        ),
        migrations.AddField(
            model_name='steps',
            name='attemts',
            field=models.ManyToManyField(related_name='steps', through='university.StudentStepAttempt', to='university.students'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.teachers'),
        ),
    ]
