# Generated by Django 5.2 on 2025-05-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.groups'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='isu_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
