# Generated by Django 5.2.1 on 2025-05-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_solutions_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutions',
            name='attempts_left',
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='solution_data',
        ),
        migrations.AlterField(
            model_name='solutions',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
