# Generated by Django 5.2.1 on 2025-05-13 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_remove_groups_group_id_alter_groups_group_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='module_id',
        ),
        migrations.AddField(
            model_name='steps',
            name='module',
            field=models.ForeignKey(db_column='module_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='university.modules'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modules',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='university.courses'),
        ),
    ]
