# Generated by Django 5.2.1 on 2025-05-13 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_steps_module_id_steps_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='module',
            field=models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='university.modules'),
        ),
    ]
