# Generated by Django 5.2.1 on 2025-06-05 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_solutions_attempts_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='university.steps')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='university.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'step')},
            },
        ),
    ]
