# Generated by Django 5.2.1 on 2025-06-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_studentstepresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentstepresult',
            unique_together=set(),
        ),
    ]
