# Generated by Django 5.2.1 on 2025-05-15 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_steps_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.studentprofile'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='lab_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
