# Generated by Django 5.2.1 on 2025-05-15 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_studentprofile_id_remove_teacherprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='step_file',
            field=models.FileField(blank=True, null=True, upload_to='files_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'pdf'])]),
        ),
    ]
