# Generated by Django 5.2.1 on 2025-05-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_steps_step_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='email',
        ),
    ]
