# Generated by Django 5.2.1 on 2025-05-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_remove_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steps',
            old_name='attemts',
            new_name='attempts',
        ),
    ]
