# Generated by Django 5.2.1 on 2025-05-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_rename_attemts_steps_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='attempts',
            field=models.ManyToManyField(related_name='step_attempts', through='university.StudentStepAttempt', to='university.studentprofile'),
        ),
    ]
