# Generated by Django 5.2.1 on 2025-05-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_alter_steps_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstepattempt',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_attempts', to='university.steps'),
        ),
        migrations.AlterField(
            model_name='studentstepattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='university.studentprofile'),
        ),
    ]
