# Generated by Django 5.2.1 on 2025-05-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_solutions_student_alter_steps_lab_number'),
        ('university', '0010_alter_studentstepattempt_step_and_more'),
    ]

    operations = [
    ]
